name = "learner"

[env.production]
name = "learner"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.jsx", "src/**/*.js", "src/**/*.css", "index.html", "*.config.js"]

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.eot", "**/*.otf", "**/*.ttf", "**/*.woff", "**/*.woff2"]
fallthrough = true
